### ISSUE TITLE
Annotations from .assembly file only display in the "scaffold_1" view, and not in the "all" view or the views for the individual scaffolds they belong to.  [BUG]

### ISSUE THREAD

**Issue by oneillkza** [theaidenlab/juicebox#975] opened 2021-11-24 01:56 UTC
**Describe the bug**
Annotations from .assembly file only display in the "scaffold_1" view, and not in the "all" view or the views for the individual scaffolds they belong to. This prevents any of the assembly tools from working correctly.

**To Reproduce**
1. Open .hic file
2. Open .assembly file
3. Annotations for scaffold boundaries do not display
4. Click scaffold_1 drop-down
5. Annotations for the whole genome are stuffed into scaffold_1
6. Click any other scaffold drop-down
7. No annotations are visible

**Expected behavior**
Scaffold boundary annotations are expected to appear in the "all" scaffold view, and possible in the views for individual scaffolds? This also seems to be a necessary step for any of the assembly tools to work, and is the likely cause for #972 

**Screenshots**
![juicebox_jbat_bug](https://user-images.githubusercontent.com/3099991/143156999-df164ef0-b8f9-418b-a0ed-ce2eff1617db.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version Juicebox 2.13.07

**Additional context**
Here's the assembly file, in case this helps:

[scaffolds_FINAL_pg.assembly.gz](https://github.com/aidenlab/Juicebox/files/7592118/scaffolds_FINAL_pg.assembly.gz)

(I couldn't find an actual spec for this file format -- it seems to be some kind of juicer-only thing?)

It was generated from the SALSA final fasta using [tools from PhaseGenomics](https://github.com/phasegenomics/juicebox_scripts )

**Comment by dudcha** [comment] 2021-11-24 02:04
Thanks for a detailed description of the issue you are experiencing. Closing since this is not a bug. Looks like you are trying to use JBAT on a sandboxes, non-assembly hic  file. Please consult Genome Assembly Cookbook (dnazoo.org/methods) on 3D-DNA tool suite usage. Thanks, -Olga

**Closed as completed by dudcha** 2021-11-24 02:04 UTC
Labels: bug
